from __future__ import annotations

from dataclasses import dataclass
import numpy as np


@dataclass(frozen=True)
class ClientReadoutSchema:
    client_id: int
    local_to_global: np.ndarray
    readout_p: float
    depol_p: float
    depth: int
    shots: int

    @property
    def n_local(self) -> int:
        return int(len(self.local_to_global))


class QuantumReadoutSimulator:
    """Backend-agnostic readout simulator.

    Replace `expected_observables` and `measure` with PennyLane/Qiskit calls
    later; the rest of the QProto-HOP protocol should not need to change.
    """

    def __init__(self, input_dim: int, n_observables: int, seed: int = 0, shot_noise_scale: float = 1.0):
        rng = np.random.default_rng(seed)
        self.input_dim = int(input_dim)
        self.n_observables = int(n_observables)
        self.shot_noise_scale = float(max(0.0, shot_noise_scale))
        self.w0 = rng.normal(0.0, 1.0 / np.sqrt(input_dim), size=(input_dim, n_observables))
        self.w1 = rng.normal(0.0, 1.0 / np.sqrt(input_dim), size=(input_dim, n_observables))
        self.bias = rng.normal(0.0, 0.15, size=(n_observables,))

    def expected_observables(self, x: np.ndarray) -> np.ndarray:
        x = np.asarray(x, dtype=np.float64)
        logits = x @ self.w0 + 0.35 * np.sin(x @ self.w1) + self.bias
        return np.tanh(logits)

    def measure(
        self,
        x: np.ndarray,
        schema: ClientReadoutSchema,
        *,
        shots: int | None = None,
        seed: int = 0,
    ) -> tuple[np.ndarray, np.ndarray]:
        rng = np.random.default_rng(seed)
        shots = int(schema.shots if shots is None else shots)
        mu = self.expected_observables(x)[:, schema.local_to_global]
        atten = (1.0 - schema.depol_p) ** max(schema.depth, 1)
        mu = np.clip((1.0 - 2.0 * schema.readout_p) * atten * mu, -1.0, 1.0)
        out_var = np.maximum(0.0, 1.0 - mu * mu)
        noise = rng.normal(0.0, self.shot_noise_scale * np.sqrt(out_var / max(shots, 1)), size=mu.shape)
        raw = np.clip(mu + noise, -1.0, 1.0)
        return raw.astype(np.float64), (out_var * self.shot_noise_scale * self.shot_noise_scale).astype(np.float64)


class PrecomputedReadoutSimulator:
    """Readout simulator for standard quantum-backend feature dumps.

    The dataset features are assumed to already be public-dictionary observable
    expectations in [-1, 1], for example generated by PennyLane or Qiskit. This
    class only applies client schema selection and finite-shot/readout noise.
    """

    def __init__(self, input_dim: int, n_observables: int, seed: int = 0, shot_noise_scale: float = 1.0):
        if input_dim < n_observables:
            raise ValueError("precomputed readout requires input_dim >= n_observables")
        self.input_dim = int(input_dim)
        self.n_observables = int(n_observables)
        self.shot_noise_scale = float(max(0.0, shot_noise_scale))

    def expected_observables(self, x: np.ndarray) -> np.ndarray:
        x = np.asarray(x, dtype=np.float64)
        return np.clip(x[:, : self.n_observables], -1.0, 1.0)

    def measure(
        self,
        x: np.ndarray,
        schema: ClientReadoutSchema,
        *,
        shots: int | None = None,
        seed: int = 0,
    ) -> tuple[np.ndarray, np.ndarray]:
        rng = np.random.default_rng(seed)
        shots = int(schema.shots if shots is None else shots)
        mu = self.expected_observables(x)[:, schema.local_to_global]
        atten = (1.0 - schema.depol_p) ** max(schema.depth, 1)
        mu = np.clip((1.0 - 2.0 * schema.readout_p) * atten * mu, -1.0, 1.0)
        out_var = np.maximum(0.0, 1.0 - mu * mu)
        noise = rng.normal(0.0, self.shot_noise_scale * np.sqrt(out_var / max(shots, 1)), size=mu.shape)
        raw = np.clip(mu + noise, -1.0, 1.0)
        return raw.astype(np.float64), (out_var * self.shot_noise_scale * self.shot_noise_scale).astype(np.float64)


def make_client_schemas(
    *,
    n_clients: int,
    n_observables: int,
    obs_per_client: int,
    overlap: float,
    shots_levels: list[int],
    readout_p: float,
    readout_std: float,
    depol_p: float,
    depol_std: float,
    depth_min: int,
    depth_max: int,
    common_policy: str = "random",
    seed: int,
) -> list[ClientReadoutSchema]:
    rng = np.random.default_rng(seed)
    obs_per_client = min(obs_per_client, n_observables)
    n_common = int(round(obs_per_client * np.clip(overlap, 0.0, 1.0)))
    if n_common <= 0:
        common = np.array([], dtype=np.int64)
    elif common_policy == "prefix":
        common = np.arange(n_common, dtype=np.int64)
    elif common_policy == "suffix":
        common = np.arange(n_observables - n_common, n_observables, dtype=np.int64)
    elif common_policy == "random":
        common = rng.choice(n_observables, size=n_common, replace=False)
    else:
        raise ValueError("common_policy must be one of: random, prefix, suffix")
    remaining_all = np.array([j for j in range(n_observables) if j not in set(common.tolist())], dtype=np.int64)
    schemas = []

    for cid in range(n_clients):
        need = obs_per_client - n_common
        if need > 0:
            extra = rng.choice(remaining_all, size=need, replace=False)
            keys = np.concatenate([common, extra])
        else:
            keys = common.copy()
        rng.shuffle(keys)
        rp = float(np.clip(rng.normal(readout_p, readout_std), 0.0, 0.25))
        dp = float(np.clip(rng.normal(depol_p, depol_std), 0.0, 0.25))
        depth = int(rng.integers(depth_min, depth_max + 1))
        shots = int(rng.choice(shots_levels))
        schemas.append(
            ClientReadoutSchema(
                client_id=cid,
                local_to_global=keys.astype(np.int64),
                readout_p=rp,
                depol_p=dp,
                depth=depth,
                shots=shots,
            )
        )
    return schemas


def shot_variance_scalar(out_var: np.ndarray, shots: int) -> float:
    return float(np.mean(np.sum(out_var, axis=1) / max(shots, 1)))


def adapt_readout(
    raw: np.ndarray,
    schema: ClientReadoutSchema,
    *,
    mode: str,
    n_observables: int,
    max_raw_dim: int,
    wrong_shift: int = 7,
) -> np.ndarray:
    """Map heterogeneous raw readouts into a protocol input domain.

    Returned vectors concatenate values and a mask, so missing observables are
    distinguishable from true zero-valued expectations.
    """
    raw = np.asarray(raw, dtype=np.float64)
    n = raw.shape[0]

    if mode == "no_schema":
        vals = np.zeros((n, max_raw_dim), dtype=np.float64)
        mask = np.zeros((n, max_raw_dim), dtype=np.float64)
        l = min(raw.shape[1], max_raw_dim)
        vals[:, :l] = raw[:, :l]
        mask[:, :l] = 1.0
        return np.concatenate([vals, mask], axis=1)

    vals = np.zeros((n, n_observables), dtype=np.float64)
    mask = np.zeros((n, n_observables), dtype=np.float64)

    if mode in {"correct", "correct_values", "correct_mask"}:
        target = schema.local_to_global
    elif mode == "wrong_schema":
        target = (schema.local_to_global + wrong_shift + schema.client_id) % n_observables
    elif mode == "forced_canonical":
        target = np.arange(schema.n_local, dtype=np.int64) % n_observables
    else:
        raise ValueError(f"Unknown adapter mode: {mode}")

    for local_j, global_j in enumerate(target):
        vals[:, global_j] += raw[:, local_j]
        mask[:, global_j] += 1.0
    nonzero = mask > 0
    vals[nonzero] /= mask[nonzero]
    mask = np.clip(mask, 0.0, 1.0)
    if mode == "correct_values":
        return vals
    if mode == "correct_mask":
        return mask
    return np.concatenate([vals, mask], axis=1)


